language: node_js
node_js:
 - "stable"
 
cache: npm

install:
 - npm ci
 
script:
 - npm run test
 -npm run build

deploy:
 provider: vps
 github-token: $GITHUB_TOKEN
 local_dir: build
 on:
  branch: main