export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";

export const SIGNUP_START = "AUTH_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "AUTH_ERROR";

export const RECEIVE_CURRENT_ROUTE_START = "RECEIVE_CURRENT_ROUTE_START";
export const RECEIVE_CURRENT_ROUTE_SUCCESS = "RECEIVE_CURRENT_ROUTE_SUCCESS";
export const RECEIVE_CURRENT_ROUTE_ERROR = "RECEIVE_CURRENT_ROUTE_ERROR";

export const SEND_PRODUCTS_REQUEST_START = "SEND_PRODUCTS_REQUEST_START";
export const SEND_PRODUCTS_REQUEST_SUCCESS = "SEND_PRODUCTS_REQUEST_SUCCESS";
export const SEND_PRODUCTS_REQUEST_ERROR = "SEND_PRODUCTS_REQUEST_ERROR";

export const CHOSEN_CATEGORY = "CHOSEN_CATEGORY";
export const CHOSEN_SUBCATEGORY = "CHOSEN_SUBCATEGORY";
export const SIDEBAR_DEFAULT = "SIDEBAR_DEFAULT";
export const UPDATE_CHOSEN_ITEMS = "UPDATE_CHOSEN_ITEMS";
