export const RENDER_SIDEBAR_ITEMS_START = "RENDER_SIDEBAR_ITEMS_START";
export const RENDER_SIDEBAR_ITEMS_SUCCESS = "RENDER_SIDEBAR_ITEMS_SUCCESS";
export const RENDER_SIDEBAR_ITEMS_ERROR = "RENDER_SIDEBAR_ITEMS_ERROR";
