export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";
export const SET_LOGIN_TOGGLE = "LOGIN/SET_LOGIN_TOGGLE";

export const SIGNUP_START = "AUTH_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "AUTH_ERROR";

export const RECEIVE_CURRENT_ROUTE_START = "RECEIVE_CURRENT_ROUTE_START";
export const RECEIVE_CURRENT_ROUTE_SUCCESS = "RECEIVE_CURRENT_ROUTE_SUCCESS";
export const RECEIVE_CURRENT_ROUTE_ERROR = "RECEIVE_CURRENT_ROUTE_ERROR";

export const SEND_PRODUCTS_REQUEST_START = "SEND_PRODUCTS_REQUEST_START";
export const SEND_PRODUCTS_REQUEST_SUCCESS = "SEND_PRODUCTS_REQUEST_SUCCESS";
export const SEND_PRODUCTS_REQUEST_ERROR = "SEND_PRODUCTS_REQUEST_ERROR";

export const SHOP_SET_DEFAULT = "SHOP_SET_DEFAULT";

export const CHOSEN_CATEGORY = "CHOSEN_CATEGORY";

export const CHOSEN_SUBCATEGORY = "CHOSEN_SUBCATEGORY";
export const SIDEBAR_DEFAULT = "SIDEBAR_DEFAULT";
export const UPDATE_CHOSEN_ITEMS = "UPDATE_CHOSEN_ITEMS";

export const COLOR = "PRODUCT/COLOR";
export const SELECT_CURRENT_ITEM = "SELECT_CURRENT_ITEM";
export const SELECT_CURRENT_ITEM_START = "SELECT_CURRENT_ITEM_START";

export const SEND_PRODUCT_REQUEST_ERROR = "SEND_PRODUCT_REQUEST_ERROR";

export const ADD_TO_CART_START = "ADD_TO_CART_START";
export const ADD_TO_CARD_INCREASE_COUNT = "ADD_TO_CARD_INCREASE_COUNT";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_ERROR = "ADD_TO_CART_ERROR";
export const TOGGLE_CART_PREVIEW = "REMOVE_CART_PREVIEW";
export const SHOW_CART_PREVIEW = "SHOW_CART_PREVIEW";
export const INCREASE_ITEM_COUNT = "INCREASE_ITEM_COUNT";
export const DECREASE_ITEM_COUNT = "DECREASE_ITEM_COUNT";
export const SET_ITEM_COUNT = "SET_ITEM_COUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";

export const SELECT_PRODUCT_PREVIEW_PARAMS = "SELECT_PRODUCT_PREVIEW_PARAMS";

export const PHOTO = "PRODUCT/PHOTOS";
export const VISITED_PRODUCTS = "PRODUCT/VISITED_PRODUCTS";

export const SET_FILTER_ITEMS = "SET_FILTER_ITEMS";
export const SET_PRICE_RANGE = "SET_PRICE_RANGE";
export const ADD_REMOVE_COLOR = "ADD_REMOVE_COLOR";
export const RESET_FILTERS = "RESET_FILTERS";
export const RESET_FILTER_ITEMS = "RESET_FILTER_ITEMS";

export const PAGINATION_ADD_MORE_ITEMS = "PAGINATION/ADD_MORE_ITEMS";
export const PAGINATION_SET_DEFAULT = "PAGINATION/SET_DEFAULT";
export const PAGINATION_SET_CONFIG = "PAGINATION/SET_CONFIG";
export const PAGINATION_ADD_MORE_ITEMS_START =
  "PAGINATION/PAGINATION_ADD_MORE_ITEMS_START";

export const SAVE_CREDIT_CARD_DETAILS = "USER/SAVE_CREDIT_CARD_DETAILS";

export const SET_ACCOUNT_ACTIVE_TAB = "ACCOUNT/SET_ACCOUNT_ACTIVE_TAB";
export const SET_LOGIN_ACTIVE_TAB = "CART/SET_LOGIN_ACTIVE_TAB";

export const CART_CHECK_DISCOUNT_CODE = "CART/CART_CHECK_DISCOUNT_CODE";
export const CART_DISCOUNT_CODE_SUCCESS = "CART/CART_DISCOUNT_CODE_SUCCESS";
export const CART_DISCOUNT_CODE_ERROR = "CART/CART_DISCOUNT_CODE_ERROR";
export const CART_DISCOUNT_RESET = "CART/CART_DISCOUNT_RESET";
export const USER_DISCOUNT_EXIST = "USER/AUTH_DISCOUNT_EXIST";
