export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGOUT_START = "AUTH_LOGOUT_START";

export const SIGNUP_START = "AUTH_START";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "AUTH_ERROR";

export const RECEIVE_CURRENT_ROUTE_START = "RECEIVE_CURRENT_ROUTE_START";
export const RECEIVE_CURRENT_ROUTE_SUCCESS = "RECEIVE_CURRENT_ROUTE_SUCCESS";
export const RECEIVE_CURRENT_ROUTE_ERROR = "RECEIVE_CURRENT_ROUTE_ERROR";

export const CHOSEN_CATEGORY = "CHOSEN_CATEGORY";
